name: Terraform Destroy

on:
  workflow_dispatch:  # 👈 manually triggered from GitHub UI

jobs:
  destroy:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Download Terraform State  #Download the tfsate file
        uses: actions/download-artifact@v3
        with:
             name: tfstate   # 👈 must match the name used in upload
             
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
